name: Create a new app

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name 
        required: true      
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range (from..to)
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: freddydk/AL-Go-Actions/ReadSettings@main
        with:
          get: type

      - name: Creating a new app
        uses: freddydk/AL-Go-Actions/CreateApp@main
        with:
          type: ${{ env.type }}
          publisher: ${{ github.event.inputs.publisher }}
          name: ${{ github.event.inputs.name }}
          idrange: ${{ github.event.inputs.idrange }}
          directCommit: ${{ github.event.inputs.directCommit }}
