name: Create release

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: App version to promote to release (default is latest)
        required: false
        default: 'latest'
      name:
        description: Name of this release
        required: true
        default: ''
      tag:
        description: Tag of this release (needs to be semantic version string https://semver.org, ex. 1.0.0)
        required: true
        default: ''
      prerelease:
        description: Prerelease (Y/N)
        required: false
        default: 'N'
      draft:
        description: Draft (Y/N)
        required: false
        default: 'N'
      createReleaseBranch:
        description: Create Release Branch (Y/N)
        required: false
        default: 'N'
      updateVersionNumber:
        description: New Version Number in main branch. Use Major.Minor for absolute change, use +Major.Minor for incremental change.
        required: false
        default: ''
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency: release

defaults:
  run:
    shell: PowerShell

jobs:
  Initialization:
    runs-on: [ windows-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go-Actions/WorkflowInitialize@main
        with:
          eventId: "DO0094"

  CreateRelease:
    runs-on: [ windows-latest ]
    needs: [ Initialization ]
    outputs:
      artifacts: ${{ steps.analyzeartifacts.outputs.artifacts }}
      upload_url: ${{ steps.createrelease.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        id: ReadSettings
        uses: freddydk/AL-Go-Actions/ReadSettings@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          get: TemplateUrl,RepoName
          getProjects: 'Y'

      - name: Check for updates to AL-Go system files
        uses: freddydk/AL-Go-Actions/CheckForUpdates@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          templateUrl: ${{ env.TemplateUrl }}

      - name: Analyze Artifacts
        id: analyzeartifacts
        run: |
          $ErrorActionPreference = "STOP"
          $projects = '${{ steps.ReadSettings.outputs.ProjectsJson }}' | ConvertFrom-Json
          $projects | out-host
          $include = @()
          $projects | ForEach-Object {
            $thisProject = $_
            if ($thisProject -and ($thisProject -ne '.')) {
              $project = $thisProject.Replace('\','_')
            }
            else {
              $project = $env:RepoName
            }
            Write-Host "Analyzing artifacts for project $project"
            $appVersion = '${{ github.event.inputs.appVersion }}'
            $headers = @{ 
                "Authorization" = "token ${{ github.token }}"
                "Accept"        = "application/json"
            }
            $allArtifacts = Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/actions/artifacts" | ConvertFrom-Json
            $artifactsVersion = $appVersion
            if ($appVersion -eq "latest") {
              $artifact = $allArtifacts.artifacts | Where-Object { $_.name -like "$project-*-Apps-*" } | Select-Object -First 1
              $artifactsVersion = $artifact.name.SubString($artifact.name.IndexOf('-Apps-')+6)
            }
            $allArtifacts.artifacts | Where-Object { $_.name -like "$project-*-Apps-$($artifactsVersion)" -or $_.name -like "$project-*-TestApps-$($artifactsVersion)" -or $_.name -like "$project-*-Dependencies-$($artifactsVersion)" } | ForEach-Object {
              $atype = $_.name.SubString(0,$_.name.Length-$artifactsVersion.Length-1)
              $atype = $atype.SubString($atype.LastIndexOf('-')+1)
              $include += $( [ordered]@{ "name" = $_.name; "url" = $_.archive_download_url; "atype" = $atype; "project" = $thisproject } )
            }
            if ($include.Count -eq 0) {
              Write-Host "::Error::No artifacts found"
              exit 1
            }
          }
          $artifacts = @{ "include" = $include }
          $artifactsJson = $artifacts | ConvertTo-Json -compress
          Add-Content -Path $env:GITHUB_OUTPUT -Value "artifacts=$artifactsJson"
          Write-Host "artifacts=$artifactsJson"

      - name: Prepare release notes
        id: createreleasenotes
        uses: freddydk/AL-Go-Actions/CreateReleaseNotes@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          tag_name: ${{ github.event.inputs.tag }}

      - name: Create release
        uses: actions/create-release@v1
        id: createrelease
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: ${{ github.event.inputs.draft=='Y' }}
          prerelease: ${{ github.event.inputs.prerelease=='Y' }}
          release_name: ${{ github.event.inputs.name }}
          tag_name: ${{ github.event.inputs.tag }}
          body: ${{ steps.createreleasenotes.outputs.releaseNotes }}

  UploadArtifacts:
    runs-on: [ windows-latest ] 
    needs: [ CreateRelease ]
    strategy:
      matrix: ${{ fromJson(needs.CreateRelease.outputs.artifacts) }}
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        uses: freddydk/AL-Go-Actions/ReadSettings@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}

      - name: Read secrets
        uses: freddydk/AL-Go-Actions/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          settingsJson: ${{ env.Settings }}
          secrets: 'NuGetContext,StorageContext'

      - name: Download artifact
        run: |
          $ErrorActionPreference = "STOP"
          Write-Host "Downloading artifact ${{ matrix.name}}"
          $headers = @{ 
              "Authorization" = "token ${{ github.token }}"
              "Accept"        = "application/vnd.github.v3+json"
          }
          Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri '${{ matrix.url }}' -OutFile '${{ matrix.name }}.zip'
          
      - name: Upload release artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.createrelease.outputs.upload_url }}
          asset_path: '${{ matrix.name }}.zip'
          asset_name: '${{ matrix.name }}.zip'
          asset_content_type: application/zip

      - name: NuGetContext
        id: nuGetContext
        if: ${{ env.NuGetContext }}
        run: |
          $ErrorActionPreference = "STOP"
          $nuGetContext = ''
          if ('${{ matrix.atype }}' -eq 'Apps') {
            $nuGetContext = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String([System.Environment]::GetEnvironmentVariable('NuGetContext')))
          }
          Add-Content -Path $env:GITHUB_OUTPUT -Value "nuGetContext=$nuGetContext"
          Write-Host "nuGetContext=$nuGetContext"

      - name: Deliver to NuGet
        uses: freddydk/AL-Go-Actions/Deliver@main
        if: ${{ steps.nuGetContext.outputs.nuGetContext }}
        env:
          deliveryContext: ${{ steps.nuGetContext.outputs.nuGetContext }}
        with:
          type: 'Release'
          projects: ${{ matrix.project }}
          deliveryTarget: 'NuGet'
          artifacts: ${{ github.event.inputs.appVersion }}
          atypes: 'Apps,TestApps'

      - name: StorageContext
        id: storageContext
        if: ${{ env.StorageContext }}
        run: |
          $ErrorActionPreference = "STOP"
          $storageContext = ''
          if ('${{ matrix.atype }}' -eq 'Apps') {
            $storageContext = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String([System.Environment]::GetEnvironmentVariable('StorageContext')))
          }
          Write-Host "Add-Content -Path $env:GITHUB_OUTPUT -Value "storageContext=$storageContext"
          Write-Host "storageContext=$storageContext"

      - name: Deliver to Storage
        uses: freddydk/AL-Go-Actions/Deliver@main
        if: ${{ steps.storageContext.outputs.storageContext }}
        env:
          deliveryContext: ${{ steps.storageContext.outputs.storageContext }}
        with:
          type: 'Release'
          projects: ${{ matrix.project }}
          deliveryTarget: 'Storage'
          artifacts: ${{ github.event.inputs.appVersion }}
          atypes: 'Apps,TestApps,Dependencies'

  CreateReleaseBranch:
    if: ${{ github.event.inputs.createReleaseBranch=='Y' }}
    runs-on: [ windows-latest ]
    needs: [ Initialization, CreateRelease, UploadArtifacts ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Release Branch
        run: |
          $ErrorActionPreference = "STOP"
          git checkout -b release/${{ github.event.inputs.tag }}
          git config user.name ${{ github.actor}}
          git config user.email ${{ github.actor}}@users.noreply.github.com
          git commit --allow-empty -m "Release branch ${{ github.event.inputs.tag }}"
          git push origin release/${{ github.event.inputs.tag }}

  UpdateVersionNumber:
    if: ${{ github.event.inputs.updateVersionNumber!='' }}
    runs-on: [ windows-latest ]
    needs: [ Initialization, CreateRelease, UploadArtifacts ]
    steps:
      - name: Update Version Number
        uses: freddydk/AL-Go-Actions/IncrementVersionNumber@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          versionNumber: ${{ github.event.inputs.updateVersionNumber }}
          directCommit: ${{ github.event.inputs.directCommit }}

  PostProcess:
    if: always()
    runs-on: [ windows-latest ]
    needs: [ Initialization, CreateRelease, UploadArtifacts, CreateReleaseBranch, UpdateVersionNumber ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Finalize the workflow
        id: PostProcess
        uses: freddydk/AL-Go-Actions/WorkflowPostProcess@main
        with:
          eventId: "DO0094"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
