name: ' Publish To AppSource'

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: App version to deliver to AppSource (current, prerelease, draft, latest or version number)
        required: false
        default: 'current'
      GoLive:
        description: Promote AppSource App to go live if it passes technical validation? (Y/N)
        required: false
        default: 'N'

permissions:
  contents: read
  actions: read

defaults:
  run:
    shell: PowerShell

jobs:
  Initialization:
    runs-on: [ windows-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v2.2
        with:
          eventId: "DO0103"

  Deliver:
    needs: [ Initialization ]
    runs-on: [ windows-latest ]
    name: Deliver to AppSource
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v2.2
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}

      - name: Read secrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v2.2
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          settingsJson: ${{ env.Settings }}
          secrets: 'AppSourceContext'

      - name: DeliveryContext
        id: deliveryContext
        run: |
          $ErrorActionPreference = "STOP"
          $contextName = 'AppSourceContext'
          $deliveryContext = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String([System.Environment]::GetEnvironmentVariable($contextName)))
          Add-Content -Path $env:GITHUB_OUTPUT -Value "deliveryContext=$deliveryContext"
          Write-Host "deliveryContext=$deliveryContext"

      - name: Deliver
        uses: microsoft/AL-Go-Actions/Deliver@v2.2
        env:
          deliveryContext: '${{ steps.deliveryContext.outputs.deliveryContext }}'
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          type: 'Release'
          projects: '*'
          deliveryTarget: 'AppSource'
          artifacts: ${{ github.event.inputs.appVersion }}
          goLive: ${{ github.event.inputs.goLive }}

  PostProcess:
    if: always()
    runs-on: [ windows-latest ]
    needs: [ Initialization, Deliver ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Finalize the workflow
        id: PostProcess
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@v2.2
        with:
          eventId: "DO0103"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
