name: Pull Request Handler

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
    branches: [ 'main' ]

defaults:
  run:
    shell: PowerShell

permissions:
  contents: read
  actions: read
  pull-requests: read

jobs:
  PullRequestHandler:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Determine Changed Files
        id: ChangedFiles
        run: |
          $ErrorActionPreference = "STOP"
          $sb = [System.Text.StringBuilder]::new()
          $headers = @{             
              "Authorization" = 'token ${{ secrets.GITHUB_TOKEN }}'
              "Accept" = "application/vnd.github.baptiste-preview+json"
          }
          $baseSHA = '${{ github.event.pull_request.base.sha }}'
          $headSHA = '${{ github.event.pull_request.head.sha }}'
          $url = "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/compare/$baseSHA...$headSHA"
          $response = Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri $url | ConvertFrom-Json
          $filesChanged = @($response.files | ForEach-Object { $_.filename })
          $location = (Get-Location).path
          $prfolder = [GUID]::NewGuid().ToString()
          Write-Host "::set-output name=prfolder::$prfolder"
          $prPath = Join-Path $location $prFolder
          New-Item -Path $prPath -ItemType Directory | Out-Null
          Write-Host "Files Changed:"
          $filesChanged | ForEach-Object {
            Write-Host -noNewLine "- $_"
            $path = Join-Path $location $_
            $newPath = Join-Path $prPath $_
            $newfolder = [System.IO.Path]::GetDirectoryName($newpath)
            $extension = [System.IO.Path]::GetExtension($path)
            $filename = [System.IO.Path]::GetFileName($path)
            if ('${{ github.event.pull_request.head.repo.full_name }}' -ne $ENV:GITHUB_REPOSITORY) {
              if ($extension -eq '.ps1' -or $extension -eq '.yaml' -or $extension -eq '.yml' -or $filename -eq "CODEOWNERS") {
                throw "Pull Request containing changes to scripts, workflows or CODEOWNERS are not allowed from forks."
              }
            }
            if (-not (Test-Path $newfolder)) {
              New-Item $newfolder -ItemType Directory | Out-Null
              Write-Host " deleted"
            }
            if (Test-Path $path) {
              Copy-Item -Path $path -Destination $newfolder -Force
              Write-Host " changed"
            }
            else {
              New-Item -Path $newfolder -name "$filename.REMOVE" -itemType File | Out-Null
            }
          }
          Set-Content -path (Join-Path $prPath "comment_id") -value '${{ steps.CreateComment.outputs.comment_id }}' -NoNewLine -Force

      - name: Upload Changed Files
        uses: actions/upload-artifact@v2
        with:
          name: Pull_Request_Files
          path: '${{ steps.ChangedFiles.outputs.prfolder }}/'
