name: Update AL-Go System Files

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (only if a change is needed)
        required: false
        default: ''
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

defaults:
  run:
    shell: PowerShell

jobs:
  Initialization:
    runs-on: [ windows-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v1.0
        with:
          eventId: "DO0098"

  Update:
    runs-on: [ windows-latest ]
    needs: [ Initialization ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v1.0
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          get: KeyVaultName,GhTokenWorkflowSecretName,TemplateUrl

      - name: Read secrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v1.0
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          settingsJson: ${{ env.Settings }}
          secrets: 'ghTokenWorkflow=${{ env.GHTOKENWORKFLOWSECRETNAME }}'

      - name: Override TemplateUrl
        run: |
          $templateUrl = '${{ github.event.inputs.templateUrl }}'
          if ($templateUrl) {
            Write-Host "Using Template Url: $templateUrl"
            Add-Content -Path $env:GITHUB_ENV -Value "TemplateUrl=$templateUrl"
          }

      - name: Update AL-Go system files
        uses: microsoft/AL-Go-Actions/CheckForUpdates@v1.0
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          token: ${{ env.ghTokenWorkflow }}
          Update: Y
          templateUrl: ${{ env.TemplateUrl }}
          directCommit: ${{ github.event.inputs.directCommit }}

  PostProcess:
    if: always()
    runs-on: [ windows-latest ]
    needs: [ Initialization, Update ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Finalize the workflow
        id: PostProcess
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@v1.0
        with:
          eventId: "DO0098"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
